// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SPC2010DemoClient {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AccountScreen")]
	public partial class AccountScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_lblAccountNumber;
		
		private MonoTouch.UIKit.UILabel __mt_lblCreditLimit;
		
		private MonoTouch.UIKit.UILabel __mt_lblCurrentBalance;
		
		private MonoTouch.UIKit.UITextField __mt_txtEmailTo;
		
		private MonoTouch.UIKit.UILabel __mt_lblLastOrder;
		
		private MonoTouch.UIKit.UILabel __mt_lblLastPayment;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("btnSendEmail:")]
		partial void btnSendEmail (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblAccountNumber")]
		private MonoTouch.UIKit.UILabel lblAccountNumber {
			get {
				this.__mt_lblAccountNumber = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblAccountNumber")));
				return this.__mt_lblAccountNumber;
			}
			set {
				this.__mt_lblAccountNumber = value;
				this.SetNativeField("lblAccountNumber", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblCreditLimit")]
		private MonoTouch.UIKit.UILabel lblCreditLimit {
			get {
				this.__mt_lblCreditLimit = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblCreditLimit")));
				return this.__mt_lblCreditLimit;
			}
			set {
				this.__mt_lblCreditLimit = value;
				this.SetNativeField("lblCreditLimit", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblCurrentBalance")]
		private MonoTouch.UIKit.UILabel lblCurrentBalance {
			get {
				this.__mt_lblCurrentBalance = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblCurrentBalance")));
				return this.__mt_lblCurrentBalance;
			}
			set {
				this.__mt_lblCurrentBalance = value;
				this.SetNativeField("lblCurrentBalance", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtEmailTo")]
		private MonoTouch.UIKit.UITextField txtEmailTo {
			get {
				this.__mt_txtEmailTo = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtEmailTo")));
				return this.__mt_txtEmailTo;
			}
			set {
				this.__mt_txtEmailTo = value;
				this.SetNativeField("txtEmailTo", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblLastOrder")]
		private MonoTouch.UIKit.UILabel lblLastOrder {
			get {
				this.__mt_lblLastOrder = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblLastOrder")));
				return this.__mt_lblLastOrder;
			}
			set {
				this.__mt_lblLastOrder = value;
				this.SetNativeField("lblLastOrder", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblLastPayment")]
		private MonoTouch.UIKit.UILabel lblLastPayment {
			get {
				this.__mt_lblLastPayment = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblLastPayment")));
				return this.__mt_lblLastPayment;
			}
			set {
				this.__mt_lblLastPayment = value;
				this.SetNativeField("lblLastPayment", value);
			}
		}
	}
}
