// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SPC2010DemoClient {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AddressScreen")]
	public partial class AddressScreen {
		
		private MonoTouch.UIKit.UIButton __mt_btnSave;
		
		private MonoTouch.UIKit.UIButton __mt_btnShowMap;
		
		private MonoTouch.UIKit.UITextField __mt_txtCity;
		
		private MonoTouch.UIKit.UITextField __mt_txtState;
		
		private MonoTouch.UIKit.UITextField __mt_txtStreet;
		
		private MonoTouch.UIKit.UITextField __mt_txtZip;
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("btnSave")]
		private MonoTouch.UIKit.UIButton btnSave {
			get {
				this.__mt_btnSave = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnSave")));
				return this.__mt_btnSave;
			}
			set {
				this.__mt_btnSave = value;
				this.SetNativeField("btnSave", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnShowMap")]
		private MonoTouch.UIKit.UIButton btnShowMap {
			get {
				this.__mt_btnShowMap = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnShowMap")));
				return this.__mt_btnShowMap;
			}
			set {
				this.__mt_btnShowMap = value;
				this.SetNativeField("btnShowMap", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtCity")]
		private MonoTouch.UIKit.UITextField txtCity {
			get {
				this.__mt_txtCity = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtCity")));
				return this.__mt_txtCity;
			}
			set {
				this.__mt_txtCity = value;
				this.SetNativeField("txtCity", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtState")]
		private MonoTouch.UIKit.UITextField txtState {
			get {
				this.__mt_txtState = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtState")));
				return this.__mt_txtState;
			}
			set {
				this.__mt_txtState = value;
				this.SetNativeField("txtState", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtStreet")]
		private MonoTouch.UIKit.UITextField txtStreet {
			get {
				this.__mt_txtStreet = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtStreet")));
				return this.__mt_txtStreet;
			}
			set {
				this.__mt_txtStreet = value;
				this.SetNativeField("txtStreet", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtZip")]
		private MonoTouch.UIKit.UITextField txtZip {
			get {
				this.__mt_txtZip = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtZip")));
				return this.__mt_txtZip;
			}
			set {
				this.__mt_txtZip = value;
				this.SetNativeField("txtZip", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
	}
}
