// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SPC2010DemoClient {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ContactScreen")]
	public partial class ContactScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UISwitch __mt_switchNewsletter;
		
		private MonoTouch.UIKit.UIButton __mt_btnCallHome;
		
		private MonoTouch.UIKit.UIButton __mt_btnCallWork;
		
		private MonoTouch.UIKit.UIButton __mt_btnEmail;
		
		private MonoTouch.UIKit.UITextField __mt_txtEmail;
		
		private MonoTouch.UIKit.UITextField __mt_txtFirstName;
		
		private MonoTouch.UIKit.UITextField __mt_txtHomePhone;
		
		private MonoTouch.UIKit.UITextField __mt_txtLastName;
		
		private MonoTouch.UIKit.UITextField __mt_txtWorkPhone;
		
		private MonoTouch.UIKit.UIButton __mt_btnSave;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("switchNewsletter")]
		private MonoTouch.UIKit.UISwitch switchNewsletter {
			get {
				this.__mt_switchNewsletter = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("switchNewsletter")));
				return this.__mt_switchNewsletter;
			}
			set {
				this.__mt_switchNewsletter = value;
				this.SetNativeField("switchNewsletter", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnCallHome")]
		private MonoTouch.UIKit.UIButton btnCallHome {
			get {
				this.__mt_btnCallHome = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnCallHome")));
				return this.__mt_btnCallHome;
			}
			set {
				this.__mt_btnCallHome = value;
				this.SetNativeField("btnCallHome", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnCallWork")]
		private MonoTouch.UIKit.UIButton btnCallWork {
			get {
				this.__mt_btnCallWork = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnCallWork")));
				return this.__mt_btnCallWork;
			}
			set {
				this.__mt_btnCallWork = value;
				this.SetNativeField("btnCallWork", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnEmail")]
		private MonoTouch.UIKit.UIButton btnEmail {
			get {
				this.__mt_btnEmail = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnEmail")));
				return this.__mt_btnEmail;
			}
			set {
				this.__mt_btnEmail = value;
				this.SetNativeField("btnEmail", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtEmail")]
		private MonoTouch.UIKit.UITextField txtEmail {
			get {
				this.__mt_txtEmail = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtEmail")));
				return this.__mt_txtEmail;
			}
			set {
				this.__mt_txtEmail = value;
				this.SetNativeField("txtEmail", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtFirstName")]
		private MonoTouch.UIKit.UITextField txtFirstName {
			get {
				this.__mt_txtFirstName = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtFirstName")));
				return this.__mt_txtFirstName;
			}
			set {
				this.__mt_txtFirstName = value;
				this.SetNativeField("txtFirstName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtHomePhone")]
		private MonoTouch.UIKit.UITextField txtHomePhone {
			get {
				this.__mt_txtHomePhone = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtHomePhone")));
				return this.__mt_txtHomePhone;
			}
			set {
				this.__mt_txtHomePhone = value;
				this.SetNativeField("txtHomePhone", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtLastName")]
		private MonoTouch.UIKit.UITextField txtLastName {
			get {
				this.__mt_txtLastName = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtLastName")));
				return this.__mt_txtLastName;
			}
			set {
				this.__mt_txtLastName = value;
				this.SetNativeField("txtLastName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtWorkPhone")]
		private MonoTouch.UIKit.UITextField txtWorkPhone {
			get {
				this.__mt_txtWorkPhone = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtWorkPhone")));
				return this.__mt_txtWorkPhone;
			}
			set {
				this.__mt_txtWorkPhone = value;
				this.SetNativeField("txtWorkPhone", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnSave")]
		private MonoTouch.UIKit.UIButton btnSave {
			get {
				this.__mt_btnSave = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnSave")));
				return this.__mt_btnSave;
			}
			set {
				this.__mt_btnSave = value;
				this.SetNativeField("btnSave", value);
			}
		}
	}
}
