// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SPC2010DemoClient {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UITableView __mt_TableView;
		
		private MonoTouch.UIKit.UINavigationController __mt_NavigationController;
		
		private MonoTouch.UIKit.UISearchDisplayController __mt_SearchController;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("btnRefreshClick:")]
		partial void btnRefreshClick (MonoTouch.UIKit.UIBarButtonItem sender);

		[MonoTouch.Foundation.Export("btnAddClick:")]
		partial void btnAddClick (MonoTouch.UIKit.UIBarButtonItem sender);

		[MonoTouch.Foundation.Export("btnEditClick:")]
		partial void btnEditClick (MonoTouch.UIKit.UIBarButtonItem sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TableView")]
		private MonoTouch.UIKit.UITableView TableView {
			get {
				this.__mt_TableView = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("TableView")));
				return this.__mt_TableView;
			}
			set {
				this.__mt_TableView = value;
				this.SetNativeField("TableView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("NavigationController")]
		private MonoTouch.UIKit.UINavigationController NavigationController {
			get {
				this.__mt_NavigationController = ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("NavigationController")));
				return this.__mt_NavigationController;
			}
			set {
				this.__mt_NavigationController = value;
				this.SetNativeField("NavigationController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SearchController")]
		private MonoTouch.UIKit.UISearchDisplayController SearchController {
			get {
				this.__mt_SearchController = ((MonoTouch.UIKit.UISearchDisplayController)(this.GetNativeField("SearchController")));
				return this.__mt_SearchController;
			}
			set {
				this.__mt_SearchController = value;
				this.SetNativeField("SearchController", value);
			}
		}
	}
}
