// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SPC2010DemoClient {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("WebBrowser")]
	public partial class WebBrowser {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIWebView __mt_webBrowser;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("webBrowser")]
		private MonoTouch.UIKit.UIWebView webBrowser {
			get {
				this.__mt_webBrowser = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("webBrowser")));
				return this.__mt_webBrowser;
			}
			set {
				this.__mt_webBrowser = value;
				this.SetNativeField("webBrowser", value);
			}
		}
	}
}
